observation_sources: scan scan_2 scan_3
scan: {sensor_frame: node_1, data_type: LaserScan, topic: /node_1/scan, marking: true, clearing: true, inf_is_valid: true,
       expected_update_rate: 1, max_obstacle_height: 1.0, min_obstacle_height: 0.0, obstacle_range: 10.0, raytrace_range: 10.0}

scan_2: {sensor_frame: node_2, data_type: LaserScan, topic: /node_2/scan, marking: true, clearing: true, inf_is_valid: true,
       expected_update_rate: 1, max_obstacle_height: 1.0, min_obstacle_height: 0.0, obstacle_range: 10.0, raytrace_range: 10.0}

scan_3: {sensor_frame: node_3, data_type: LaserScan, topic: /node_3/scan, marking: true, clearing: true, inf_is_valid: true,
       expected_update_rate: 1, max_obstacle_height: 1.0, min_obstacle_height: 0.0, obstacle_range: 10.0, raytrace_range: 10.0}

plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
